package com.wedding.system.model;

public class Guest {

    private int id;
    private int bookingId;
    private String name;
    private String contact;
    private String category;        // family, friend, colleague...
    private String guestCode;       // random code, generated by the system, used to "log in"
    private String rsvpStatus;      // PENDING, ACCEPTED, DECLINED
    private String dietaryRestrictions;
    private boolean plusOne;
    private int familyMembersCount = 1;

    public Guest() {
    }

    public Guest(int id, int bookingId, String name, String contact, String category,
                 String guestCode, String rsvpStatus, String dietaryRestrictions, boolean plusOne, int familyMembersCount) {
        this.id = id;
        this.bookingId = bookingId;
        this.name = name;
        this.contact = contact;
        this.category = category;
        this.guestCode = guestCode;
        this.rsvpStatus = rsvpStatus;
        this.dietaryRestrictions = dietaryRestrictions;
        this.plusOne = plusOne;
        this.familyMembersCount = familyMembersCount;
    }

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getBookingId() { return bookingId; }
    public void setBookingId(int bookingId) { this.bookingId = bookingId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getContact() { return contact; }
    public void setContact(String contact) { this.contact = contact; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getGuestCode() { return guestCode; }
    public void setGuestCode(String guestCode) { this.guestCode = guestCode; }

    public String getRsvpStatus() { return rsvpStatus; }
    public void setRsvpStatus(String rsvpStatus) { this.rsvpStatus = rsvpStatus; }

    public String getDietaryRestrictions() { return dietaryRestrictions; }
    public void setDietaryRestrictions(String dietaryRestrictions) { this.dietaryRestrictions = dietaryRestrictions; }

    public boolean isPlusOne() { return plusOne; }
    public void setPlusOne(boolean plusOne) { this.plusOne = plusOne; }

    public int getFamilyMembersCount() { return familyMembersCount; }
    public void setFamilyMembersCount(int familyMembersCount) { this.familyMembersCount = familyMembersCount; }
}
